import type { ParsedModel } from './types.js';

/** Serialize a ParsedModel as a portable ES module for validator consumers. */
export function serializeParsedModelModule(model: ParsedModel): string {
  const json = JSON.stringify(model, null, 2)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  return `// Generated by sysml-parser. Do not edit manually.\nexport const parsedModel = ${json};\n\nexport default parsedModel;\n`;
}
